# Generated by Django 4.2.5 on 2023-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_info', models.CharField(blank=True, max_length=255, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=255, null=True)),
                ('positive_seller_ratings', models.CharField(blank=True, max_length=20, null=True)),
                ('ship_on_time', models.CharField(blank=True, max_length=20, null=True)),
                ('chat_response_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('brand_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_spec', models.CharField(blank=True, max_length=50, null=True)),
                ('image_links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
